environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 10
install:
  - ps: Install-Product node $env:nodejs_version
  - npm config set loglevel warn
  - npm install --silent
  - npm install -g typescript
test_script:
  - npm run build
  - npm test
build: off
cache:
  - node_modules
