environment:
  matrix:
    - nodejs_version: 14
    - nodejs_version: 16
    - nodejs_version: 18
    - nodejs_version: 20
install:
  - ps: Install-Product node $env:nodejs_version
  - npm config set loglevel warn
  - npm install --silent
test_script:
  - npm run build
  - npm test
build: on
cache:
  - node_modules
