environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 10
    - nodejs_version: 12
    - nodejs_version: 14
    - nodejs_version: 16
install:
  - ps: Install-Product node $env:nodejs_version
  - npm config set loglevel warn
  - npm install --silent
  - npm install -g typescript
test_script:
  - npm run build
  - npm test
build: on
cache:
  - node_modules
